### ISSUE TITLE
Legibility Rework

### ISSUE THREAD

**Issue by WayneEDick** [w3c/low-vision-a11y-tf#37]
<h3>Perceiving of Text and Reading</h3>  

<p>http://w3c.github.io/low-vision-a11y-tf/requirements.html#perceiving</>
<p>Legibility identifies the suitability of text for reading. It measures perception, not comprehension. Text can be legible, but poor authorship may render it unreadable.</p>

<p>A person may be able to distinguish letters at a given point size on a vision test when reading one letter at a time, but the person may not be able to read blocks of text composed of the same letters. This is because the eye chart measures the extreme lower limit of symbol perception, it does not measure legibility. </p>

<p>Many factors influence legibility such as font size and style, contrast level, spacing of letters and line lengths. When the text is ill formed for reading but can be read, slowly and with many errors, we say that it is barely legible. The small print with poor contrast found on legal disclaimers is an example of barely legible text. </p>

<p>When the print is of a sufficiently large size for the font in use; the letters and words are spaced well enough to promote character recognition; lines are of an appropriate length, and lines are separated enough to promote easy tracking from line to line, we say the text is legible. The state of legibility will vary with the individual. One person may require larger print. Another may need higher contrast. Legibility is a state of perceptibility that supports reading, but it is not constant across people. Text that can be read rapidly and accurately is legible.</p>

<p>We have seen that some text is barely legible, but even legible text may not be enough to support the reading requirements of employment or social interaction. Text can support rapid and accurate reading, but may be difficult to read for long periods of time. That is, the reader can distinguish letters and words with high efficiency, but some property of the text like excessive or insufficient brightness or multiple column layout may make it difficult to sustain reading for extended time. Text in this format would not be a good choice for reading. When text is legible and it is presented in a format that supports reading for an extended period of time we call it sustainable.  </p>

<p>Each individual with low vision needs sustainable text to read and at the present time this is very difficult to find. The typographic properties required to sustain reading for one person with low vision may not support sustainability for another. Thus, the low vision users must have the capability to manipulate typographic properties to support their personal sustainability needs.</p>

**Comment by shawna-slh** [comment]
I think this is an excellent draft of a separate piece on legibility!

The Task Force decided to keep the main User Needs document succinct to cover what the primary target audience needs to know, and to put additional information in separate pages. This keeps the main document shorter and more focused, and also allows us to update the information in separate pages more easily. [/me doesn't dig through minutes to find this decision :-]

I considered the overall structure of the document, and:
1. I think we had this issue in the wrong section -- maybe it should go under User Needs instead of Function Vision.
2. I wonder if we even need to define or explain "legibility" in this document? It's not a jargony word, and we're not using it in a way that is substantially different from common definitions. ... actually we're only using it **one** other place, and we don't need it there. (although we do have "legible" one place)
3. I do think we need to explain the issue briefly and clearly, though. I've taken a pass at that in a separate branch ([diff view](https://github.com/w3c/low-vision-a11y-tf/pull/44/files))

In the **[branch with User Needs section edited](https://rawgit.com/w3c/low-vision-a11y-tf/user_need-legibility/requirements.html#user-needs)**, see the Note and the paragraph under it.

Thoughts?

**Comment by WayneEDick** [comment]
I'm thinking we need some detail on legibility. 13 of our 24 user needs are based on this concept.
People run into a lot of difficulty understanding the subtle differences between perceiving symbols, barely making out text, being able to read text rapidly and error free, and being able to read rapidly, error free and for a sufficient duration to finish work.
The concept of sustainable text to represent the fully functional text is mine, but as a group we can coin a term to describe a state of legibility that the web has made possible for everyone.

**Comment by shawna-slh** [comment]
This is good: "the difference between barely making out text; being able to read text rapidly and error free; and being able to read rapidly, error free and for a sufficient duration to finish work."
The latter point was missing. I've added draft info to try to capture it in both the Note and the paragraph under it.
I think it could use tweaking - I'll keep playing with it and look forward to others' ideas.

(I'm not sure that we want this document to try to coin new terms?)

**Comment by shawna-slh** [comment]
LVTF resolved to accept revision to User  Needs document in [6 April telecon (agenda 2)](https://www.w3.org/2016/04/06-lvtf-minutes.html#item02)

Can also have separate document that explores the issues in more detail, as the top of this thread.
