### ISSUE TITLE
3.3.4 capitalization - orthography

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#65]
from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0002.html
Orthography
Take care of a correct orthography! It is very important for legibility. Writing in dialect expressions or generally in lowercase letters and similar gags off habit disturb the reading process.
Solely lowercase letters are more relevant in German and other languages than in English.

**Comment by allanj-uaag** [comment]
Comment is from a non-native English speaker. Wonder if he is talking about avoiding camelCase?
I get the avoid  "dialect expressions" (which I take to mean "idioms"). he mentions lowercase several times - could be "don't use all caps" - but might be something else.

**Comment by awkawk** [comment]
Is this directly affecting low-vision users or might this be more an issue for the COGA group to review?  Perhaps he can provide more detail about the issue?

**Comment by shawna-slh** [comment]
In German, all nouns are capitalized - throughout sentences, etc. He means if words are properly capitalized, then they should be capitalized.

This improves readability/usability for everyone. I assume it is most important for people with certain types of cognitive disabilities. So, yea, I think we should pass this onto COGA.

It is somewhat related to low vision because it is easier to recognize words when properly capitalized. However, I'm leaning towards saying it doesn't quite meet the threshold of being more of an issue for people with low vision than for everybody...

**Comment by lauracarlson** [comment]
Agree to pass this to COGA.

**Comment by ghost** [comment]
completely agree with pass to COGA

**Comment by shawna-slh** [comment]
Resolved in 2 June telecon.
